# Overview

This document provides an introduction to [occupancy models](https://www.nps.gov/olym/learn/nature/upload/OccupancyModelFactSheet.pdf) in [Stan](http://mc-stan.org/).
The terms occupancy models and occurrence models can be used synonymous from a statistical and programming perspective, but can have important ecological differences from a scientific perspective. 
Both terms are used interchangeably within this document unless specifically indicated that one term is appropriate for a specific use.

## Motivation 

This document was created help collaborators learn how program occupancy models in Stan. 
Occupancy models can be difficult to program in Stan because they have discrete latent variables (i.e., the site-level occupancy).
However, compared to other Bayesian programs, Stan can offer better [performance](http://andrewgelman.com/wp-content/uploads/2014/06/stan-overview-dauphine-2014.pdf) (e.g., more rapidly fitting models, converging when other models could not, fewer iterations required).

## Prerequisite knowledge and background 

This tutorials assumes the reader is familiar with R, occupancy models, and Bayesian statistics. Some base knowledge of Stan would be helpful, even if it is just completing the schools "hello world" [example](https://github.com/stan-dev/rstan/wiki/RStan-Getting-Started). 
This tutorial builds upon a previous [example tutorial](https://github.com/stan-dev/example-models/blob/master/misc/ecology/occupancy/occupancy.stan), which I helped to update. 
Another [tutorial](https://mbjoseph.github.io/posts/2018-12-27-dynamic-occupancy-models-in-stan/) I found did not use current Stan syntax. 
Last, [a multi-species tutorial exists](http://mc-stan.org/users/documentation/case-studies/dorazio-royle-occupancy.html), but is beyond the (current) scope of this tutorial 


## Summary of tutorial 

The introduction covers a brief overview of occupancy models, logistic regression in Stan and R, and matrix notation in R. 
Next, two-level occupancy models are introduced.
Following this, three-level occupancy models are introduced.
More topics may be included (e.g., changing variance structures or correlated estimates) as I have time or need to program these models.
